### ISSUE TITLE
Preferences crash

### ISSUE THREAD

**Issue by JamieBerghmans** [semvis123/Sonitus#2] opened 2021-08-15 15:06 UTC
On a fresh install of Sonitus, preferences crash with the below crash log.

Devices tested:
iPhone 11 Pro iOS 14.3RC (Running Taurine 1.0.4)
iPhone X iOS 14.2 (Running Unc0ver 6.2.0)

Crash log: https://ghostbin.com/paste/gNkAd

**Comment by JamieBerghmans** [comment] 2021-08-15 15:12
After further testing, this only seems to happen with Shuffle (a widely used preference organizer) installed.

**Comment by semvis123** [comment] 2021-08-15 16:07
Doesn't seem to be caused by shuffle, because I'm using shuffle myself without any issues (IPhone X 14,3 Taurine). 
Installing Preferred didn't cause a crash either.
But I will look into it.
Thanks :)

**Comment by JamieBerghmans** [comment] 2021-08-15 16:17
Do you have "Insert Tables" turned on? Just turned it off and then it works, but as soon as I turn it back on it breaks again.

**Comment by semvis123** [comment] 2021-08-15 17:05
That's indeed the cause of the crash, once I enabled it the preferences bundle started crashing.

**Comment by semvis123** [comment] 2021-08-15 17:46
Should be fixed in https://github.com/semvis123/Sonitus/commit/305b1c063b1de0f60bbc7aecb936efe32efeecdd

**Comment by semvis123** [comment] 2021-08-15 18:01
Release v1.0.1 fixed this issue

**Closed by semvis123** 2021-08-15 18:01 UTC
